<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
	  <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\file.png" />
    <None Remove="Resources\folder.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
    <PackageReference Include="Microsoft.Extensions.Logging"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Console"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Inf\Inf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\file.png" />
    <Resource Include="Resources\folder.png" />
  </ItemGroup>

    <PropertyGroup>
	    <ApplicationIcon>Resources\logo.ico</ApplicationIcon>
	    <PackageReadmeFile>README.md</PackageReadmeFile>
	    <PackageLicenseFile>LICENSE</PackageLicenseFile>
	    <PackageIcon>icon.png</PackageIcon>
	    <Authors>github.com/filippov112</Authors>
    </PropertyGroup>

</Project>
